name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.11"

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Install Ganache
      run: npm install -g ganache-cli@6.12.2

    - run: poetry install

    - run: poetry run pytest
